### PR TITLE
added support for "ooTextFile short"-style textgrid

### PR DESCRIPTION
**Pull request by seanpue**
Quick fix for #11 to allow an alternative short textgrid header.

### CODE REVIEW

**Comment by mwlodarczak** [comment]
"A. Sean Pue" <notifications@github.com> writes:

> Quick fix for #11 to allow an alternative short textgrid header.

Thanks for you pull request! Is this alternative short TextGrid header
format supported by Praat itself?

Marcin

**Comment by seanpue** [comment]
Yes, it's still supported. It appears to be just a slightly different and older format for the short TextGrid header. The Penn Forced Aligner writes in this format, which is where I came across it. Praat reads it without any problems. 

It's still mentioned in the header file here: https://github.com/praat/praat/blob/master/sys/Data.h under ```Data_writeToShortTextFile``` ~ line 152 as ```The first line is 'File type = "ooTextFile short"'.```

It's referred to as "oo" format in the actual file reading code here: https://github.com/praat/praat/blob/master/sys/Data.cpp in ```Data_readFromTextFile (MelderFile file)``` ~ line 189. 

I don't know the history of Praat well enough to comment any further, but I'm sure we could ask. :) 

Sean

**Comment by mwlodarczak** [comment]
I have added an alternative fix in the altshort branch. Could you please 
check whether it works as expected for the old header format?

Marcin

**Comment by seanpue** [comment]
Sorry! I missed this thread. This is working, thanks!

**Comment by mwlodarczak** [comment]
On Fri, Dec 15, 2017 at 12:30:04PM +0000, A. Sean Pue wrote:
>Sorry! I missed this thread. This is working, thanks!

Thanks! I have merged it into master.
Marcin

**Comment by hbuschme** [comment]
This is now available in release 1.4.4.

**Comment by hbuschme** [comment]
This is now available in release 1.4.4.

**Pull request closed without merging**
