### PR TITLE
Support reading and writing from/to openned file handlers.

### PR DESCRIPTION
**Pull request by chaiko**
Such as network files, StringIO, etc.

### CODE REVIEW

**Comment by chaiko** [comment]
Hi there, would you please take a look at this pull request?

**Comment by mwlodarczak** [comment]
Thanks for this! Could you please update the docstring as well?

**Comment by chaiko** [comment]
> Thanks for this! Could you please update the docstring as well?

Done.

**Comment by chaiko** [comment]
Thanks for merging. Could you make a pip release to include it?

**Comment by hbuschme** [comment]
A new release 1.5 was created and is now available via pip

**Comment by chaiko** [comment]
Awesome!

**Pull request merged**
